const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("desktopPet", {
  studioOpen: () => ipcRenderer.invoke("studio-open"),
  studioStatus: () => ipcRenderer.invoke("studio-status"),
  studioTheme: () => ipcRenderer.invoke("studio-theme"),
  studioGenerate: (input) => ipcRenderer.invoke("studio-generate", input),
  studioPhotos: () => ipcRenderer.invoke("studio-photos"),
  studioKey: () => ipcRenderer.invoke("studio-key"),
  studioSave: () => ipcRenderer.invoke("studio-save"),
  updateStatus: () => ipcRenderer.invoke("update-status"),
  checkUpdate: () => ipcRenderer.invoke("update-check"),
  downloadUpdate: () => ipcRenderer.invoke("update-download"),
  installUpdate: () => ipcRenderer.invoke("update-install"),
  onUpdate: (fn) => ipcRenderer.on("update-state", (_, value) => fn(value)),
  bounds: (rects) => ipcRenderer.send("pet-bounds", rects),
  drag: (value) => ipcRenderer.send("pet-drag", !!value),
  calendar: () => ipcRenderer.invoke("calendar-get"),
  state: (value) => ipcRenderer.send("pet-state", value),
  command: (name) => ipcRenderer.send("dock-command", name),
  panel: (expanded) => ipcRenderer.invoke("dock-panel", !!expanded),
  dockDrag: (phase) => ipcRenderer.send("dock-drag", phase),
  shortcut: () => ipcRenderer.invoke("desktop-shortcut"),
  quit: () => ipcRenderer.send("rabbit-quit"),
  onAction: (fn) => ipcRenderer.on("pet-action", (_, value) => fn(value)),
  onCursor: (fn) => ipcRenderer.on("pet-cursor", (_, value) => fn(value)),
  onState: (fn) => ipcRenderer.on("pet-state", (_, value) => fn(value)),
});
